install! 'cocoapods', :warn_for_unused_master_specs_repo => false
platform :ios, '15.0'
use_frameworks!

target 'MarkdownKitExample' do
  
  pod 'MarkdownKit', :path => '../MarkdownKit.podspec'
  
end
